// Generated by CoffeeScript 1.6.2
(function() {
  var http, server;

  http = require('http');

  server = http.createServer(function(request, response) {
    request.addListener('end', function() {});
    response.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    response.write('Hello Coffee!');
    return response.end();
  });

  server.listen(8000);

  console.log('Server running at http://localhost:8000/');

}).call(this);

//@ sourceMappingURL=app.map
